name: terrain_carve
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - scipy
  - rasterio
  - requests
  - geopy
  - trimesh
  - matplotlib
  - pip
  - pip:
    - elevation
    - py3dep
    - pyproj
